const ASSET = './assets/';
const pieceDefs = [
  {id:'head', label:'头部', src:'head-front.png', slot:'head', x:12, y:8, w:112, h:112, placed:{x:0,y:0,w:100,h:100}, wrongMessage:'头要对着缝。'},
  {id:'seal', label:'胸口封纸', src:'seal.png', slot:'seal', x:58, y:36, w:62, h:126, placed:{x:0,y:0,w:54,h:104}, wrongMessage:'封纸要最后落下。'},
  {id:'torso', label:'躯干', src:'paper-doll-parts.png', crop:{x:1150,y:700,w:720,h:820}, slot:'torso', x:12, y:35, w:118, h:150, placed:{x:0,y:0,w:100,h:160}, wrongMessage:'衣领下的红线没有接上。'},
  {id:'arm-left', label:'左臂', src:'paper-doll-parts.png', crop:{x:680,y:665,w:390,h:720}, slot:'arm-left', x:44, y:9, w:70, h:128, placed:{x:0,y:0,w:56,h:148}, wrongMessage:'这只手的针孔不对。'},
  {id:'arm-right', label:'右臂', src:'paper-doll-parts.png', crop:{x:1830,y:665,w:390,h:720}, slot:'arm-right', x:33, y:52, w:70, h:128, placed:{x:0,y:0,w:56,h:148}, wrongMessage:'另一只手还在等它。'},
  {id:'leg-left', label:'左腿', src:'paper-doll-parts.png', crop:{x:1110,y:1830,w:390,h:920}, slot:'leg-left', x:50, y:54, w:70, h:165, placed:{x:0,y:0,w:57,h:188}, wrongMessage:'腿上的缝线断了。'},
  {id:'leg-right', label:'右腿', src:'paper-doll-parts.png', crop:{x:1500,y:1830,w:390,h:920}, slot:'leg-right', x:27, y:56, w:70, h:165, placed:{x:0,y:0,w:57,h:188}, wrongMessage:'方向反了。'}
];
const state={placed:new Set(), mistakes:0, hints:2, checked:false, success:false, drag:null};
const $=s=>document.querySelector(s); const tray=$('#tray'), playfield=$('#playfield'), board=$('#dollBoard');
const imgCache={};
function loadImage(src){if(imgCache[src])return Promise.resolve(imgCache[src]);return new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>{imgCache[src]=im;resolve(im)};im.onerror=reject;im.src=ASSET+src})}
function drawPieceCanvas(piece, el){const canvas=document.createElement('canvas');canvas.width=piece.crop?piece.crop.w:1024;canvas.height=piece.crop?piece.crop.h:1024;canvas.style.imageRendering='pixelated';el.appendChild(canvas);loadImage(piece.src).then(im=>{const c=canvas.getContext('2d');c.imageSmoothingEnabled=false;if(piece.crop)c.drawImage(im,piece.crop.x,piece.crop.y,piece.crop.w,piece.crop.h,0,0,canvas.width,canvas.height);else c.drawImage(im,0,0,canvas.width,canvas.height);cleanCheckerboard(canvas)})}
function cleanCheckerboard(canvas){const c=canvas.getContext('2d'),d=c.getImageData(0,0,canvas.width,canvas.height),a=d.data;for(let i=0;i<a.length;i+=4){const mx=Math.max(a[i],a[i+1],a[i+2]),mn=Math.min(a[i],a[i+1],a[i+2]);if(mx-mn<=12&&mn>=220)a[i+3]=0}c.putImageData(d,0,0)}
function addCleanAsset(id,src){const host=document.getElementById(id),canvas=document.createElement('canvas');canvas.width=1024;canvas.height=1024;canvas.style.width='100%';canvas.style.height='100%';canvas.style.imageRendering='pixelated';host.style.backgroundImage='none';host.appendChild(canvas);loadImage(src).then(im=>{const c=canvas.getContext('2d');c.imageSmoothingEnabled=false;c.drawImage(im,0,0,1024,1024);cleanCheckerboard(canvas)})}
function makePiece(piece){const el=document.createElement('div');el.className='piece';el.dataset.id=piece.id;el.setAttribute('aria-label',piece.label);el.title=`${piece.label}：拖到轮廓上，点击旋转`;el.style.width=piece.w+'px';el.style.height=piece.h+'px';el.style.left=piece.x+'%';el.style.top=piece.y+'%';drawPieceCanvas(piece,el);tray.appendChild(el);bindPiece(el,piece);return el}
function bindPiece(element,piece){element.addEventListener('pointerdown',event=>{if(state.success)return;event.preventDefault();const rect=element.getBoundingClientRect();state.drag={element,piece,dx:event.clientX-rect.left,dy:event.clientY-rect.top,fromTray:!state.placed.has(piece.id)};element.setPointerCapture?.(event.pointerId);element.classList.add('dragging')});element.addEventListener('pointermove',event=>{if(!state.drag||state.drag.element!==element)return;const parent=element.parentElement.getBoundingClientRect();element.style.left=(event.clientX-parent.left-state.drag.dx)+'px';element.style.top=(event.clientY-parent.top-state.drag.dy)+'px';highlightTarget(piece,event.clientX,event.clientY)});element.addEventListener('pointerup',event=>{if(!state.drag||state.drag.element!==element)return;const fromTray=state.drag.fromTray;state.drag=null;element.classList.remove('dragging');const preferred=document.querySelector('.target-slot[data-slot=\"'+piece.slot+'\"]');const pr=preferred.getBoundingClientRect();const nearPreferred=Math.hypot(event.clientX-(pr.left+pr.width/2),event.clientY-(pr.top+pr.height/2))<Math.max(180,Math.max(pr.width,pr.height)*1.65);const target=nearPreferred?preferred:getDropTarget(event.clientX,event.clientY,piece);clearHighlights();if(target&&target.dataset.slot===piece.slot)placePiece(element,piece,target);else if(target)wrongPiece(element,piece,'位置不对，再看看针孔和缝线。');else if(fromTray)returnToTray(element,piece);else snapBackPlaced(element,piece)});element.addEventListener('click',event=>{if(event.detail===0||state.drag||!state.placed.has(piece.id))return;const rotation=(Number(element.dataset.rotation||0)+90)%360;element.dataset.rotation=rotation;element.style.transform='rotate('+rotation+'deg)'})}

function resetPiecePosition(element,piece){element.style.left=piece.x+'%';element.style.top=piece.y+'%'}
function getDropTarget(x,y,piece){const preferred=piece?.slot?document.querySelector('.target-slot[data-slot=\"'+piece.slot+'\"]'):null;if(preferred){const r=preferred.getBoundingClientRect(),inside=x>=r.left-42&&x<=r.right+42&&y>=r.top-42&&y<=r.bottom+42;if(inside)return preferred}let closest=null,distance=Infinity;document.querySelectorAll('.target-slot').forEach(slot=>{const rect=slot.getBoundingClientRect(),d=Math.hypot(x-(rect.left+rect.width/2),y-(rect.top+rect.height/2)),allow=Math.max(95,Math.max(rect.width,rect.height)*1.1);if(d<allow&&d<distance){closest=slot;distance=d}});return closest}

function highlightTarget(piece,x,y){clearHighlights();const target=getDropTarget(x,y,piece);if(target)target.classList.add('is-hover')}
function clearHighlights(){document.querySelectorAll('.target-slot').forEach(slot=>slot.classList.remove('is-hover'))}
function snapBackPlaced(element,piece){const target=document.querySelector('.target-slot[data-slot="'+piece.slot+'"]');if(!target)return;const boardRect=board.getBoundingClientRect(),targetRect=target.getBoundingClientRect();element.style.left=(targetRect.left-boardRect.left+targetRect.width/2-element.offsetWidth/2)+'px';element.style.top=(targetRect.top-boardRect.top+targetRect.height/2-element.offsetHeight/2)+'px'}
function returnToTray(element,piece){if(element.parentElement!==tray)tray.appendChild(element);element.classList.remove('placed');element.style.width=piece.w+'px';element.style.height=piece.h+'px';element.style.transform='';element.dataset.rotation='0';resetPiecePosition(element,piece);state.placed.delete(piece.id);document.querySelector('.target-slot[data-slot="'+piece.slot+'"]')?.classList.remove('is-filled');updateProgress()}
function placePiece(element,piece,target){const boardRect=board.getBoundingClientRect(),targetRect=target.getBoundingClientRect();element.classList.add('placed');board.appendChild(element);const scale=Math.min((targetRect.width*.88)/element.offsetWidth,(targetRect.height*.88)/element.offsetHeight);element.style.width=Math.max(32,element.offsetWidth*scale)+'px';element.style.height=Math.max(42,element.offsetHeight*scale)+'px';element.style.left=(targetRect.left-boardRect.left+targetRect.width/2-element.offsetWidth/2)+'px';element.style.top=(targetRect.top-boardRect.top+targetRect.height/2-element.offsetHeight/2)+'px';target.classList.add('is-filled');state.placed.add(piece.id);updateProgress();flashStatus(piece.label+'已归位');if(state.placed.size===pieceDefs.length)flashStatus('所有部件已归位，点击“验合”')}

function wrongPiece(el,piece,msg){const wasPlaced=state.placed.has(piece.id);state.mistakes++;el.classList.add('wrong');setTimeout(()=>el.classList.remove('wrong'),350);if(wasPlaced)snapBackPlaced(el,piece);else returnToTray(el,piece);showToast(msg);flashStatus('纸人似乎动了一下',true);if(state.mistakes===2){$('#creepyFace').classList.add('show');setTimeout(()=>$('#creepyFace').classList.remove('show'),1800)}}
function updateProgress(){$('#progressText').textContent=`${state.placed.size} / ${pieceDefs.length} 已归位`;}
function flashStatus(text,alert=false){$('#statusText').textContent=text;$('#statusDot').className='status-dot '+(alert?'alert':'');}
function showToast(text){const t=$('#toast');t.textContent=text;t.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>t.classList.remove('show'),2200)}
function shufflePieces(){pieceDefs.forEach((p,i)=>{const el=document.querySelector(`[data-id="${p.id}"]`);if(!el)return;if(el.parentElement!==tray)tray.appendChild(el);el.classList.remove('placed','wrong');el.style.transform='';el.dataset.rotation='0';el.style.width=p.w+'px';el.style.height=p.h+'px';el.style.left=(8+(i*17)%72)+'%';el.style.top=(7+((i*29)%70))+'%';});document.querySelectorAll('.target-slot').forEach(t=>t.classList.remove('is-filled'));state.placed.clear();state.mistakes=0;state.checked=false;updateProgress();flashStatus('等待纸身归位');$('#creepyFace').classList.remove('show');$('#successHand').classList.remove('show');}
function checkPuzzle(){if(state.success)return;if(state.placed.size<pieceDefs.length){flashStatus('纸身还没有归位完整',true);showToast(`还缺 ${pieceDefs.length-state.placed.size} 个部件`);return}state.checked=true;const order=['head','torso','seal','arm-left','arm-right','leg-left','leg-right'];const ok=order.every(id=>state.placed.has(id));if(!ok){wrongPiece(document.querySelector(`[data-id="${order.find(id=>!state.placed.has(id))}"]`),pieceDefs.find(p=>p.id===order.find(id=>!state.placed.has(id))),'纸人的缝线没有连起来。');return}completePuzzle()}
function completePuzzle(){state.success=true;flashStatus('纸人完成了。它指向右边。');$('#statusDot').className='status-dot good';$('#successHand').classList.add('show');showToast('纸人抬起了手');setTimeout(()=>$('#veil').classList.add('show'),900);window.parent?.postMessage({type:'completed',puzzleId:'paper_doll_01',mistakes:state.mistakes,routeHint:'right'},'*')}
function showHint(){if(!state.hints){showToast('线索已经沉默了。');return}state.hints--;$('#hintBtn small').textContent='剩余 '+state.hints+' 次';const order=['torso','head','arm-left','arm-right','leg-left','leg-right','seal'];const next=order.find(id=>!state.placed.has(id))||'seal';const piece=pieceDefs.find(item=>item.id===next),target=document.querySelector('.target-slot[data-slot="'+piece.slot+'"]');document.querySelectorAll('.hint-active').forEach(node=>node.classList.remove('hint-active'));target?.classList.add('hint-active');document.querySelector('[data-id="'+piece.id+'"]')?.classList.add('hint-active');const messages={torso:'提示：先放躯干，衣领缺口朝上。',head:'提示：头部要对准最上方的圆形轮廓。',seal:'提示：封纸要覆盖胸口中央的窄框，并且最后放置。','arm-left':'提示：左臂接在纸人画面左侧肩部。','arm-right':'提示：右臂的针孔对准画面右侧肩部。','leg-left':'提示：鞋尖朝下，对准画面左侧长框。','leg-right':'提示：另一条腿与左腿保持对称。'};showToast(messages[next]);clearTimeout(showHint.timer);showHint.timer=setTimeout(()=>document.querySelectorAll('.hint-active').forEach(node=>node.classList.remove('hint-active')),4300)}

function exitGame(){window.parent?.postMessage({type:'exit',puzzleId:'paper_doll_01',mistakes:state.mistakes},'*');showToast('已退出谜题')}
addCleanAsset('successHand','arm-pointing.png'); addCleanAsset('creepyFace','head-side.png'); pieceDefs.forEach(makePiece);shufflePieces();$('#checkBtn').addEventListener('click',checkPuzzle);$('#resetBtn').addEventListener('click',shufflePieces);$('#hintBtn').addEventListener('click',showHint);$('#exitBtn').addEventListener('click',exitGame);$('#continueBtn').addEventListener('click',()=>{$('#veil').classList.remove('show');window.parent?.postMessage({type:'close',puzzleId:'paper_doll_01',result:'success'},'*')});window.addEventListener('keydown',e=>{if(e.key==='Escape')exitGame();if(e.key==='Enter')checkPuzzle()});window.addEventListener('message',e=>{if(e.data?.type==='start'){window.parent?.postMessage({type:'ready',puzzleId:'paper_doll_01'},'*')}});window.parent?.postMessage({type:'ready',puzzleId:'paper_doll_01'},'*');




