const $=id=>document.getElementById(id), canvas=$('board'),ctx=canvas.getContext('2d');
const atlas=new Image();atlas.src='assets/horror-atlas.png';
const foods=[['apple','腐烂果实',10],['eye','血眼',20],['heart','心脏',30],['skull','头骨',40],['lantern','幽魂灯',50],['box','诅咒盒',60]];
const TARGET_SCORE=150;
const crops={head:[880,110,120,73],body:[1002,122,47,49],apple:[716,651,113,139],eye:[878,659,108,131],heart:[1033,635,103,156],skull:[1166,678,96,109],lantern:[1297,635,100,155],box:[1437,672,118,119]};
const sprites={};let snake,dir,queue=[],food,score=0,index=0,ward=false,status='ready',last=0,best=0;
try{best=Number(localStorage.getItem('horror-snake-best'))||0}catch{}
const dirs={up:{x:0,y:-1},down:{x:0,y:1},left:{x:-1,y:0},right:{x:1,y:0}};
function spawn(){const free=[];for(let y=0;y<18;y++)for(let x=0;x<18;x++)if(!snake.some(p=>p.x===x&&p.y===y))free.push({x,y});if(!free.length){finish(true);return}food=free[Math.floor(Math.random()*free.length)]}
function reset(play=false){snake=[{x:8,y:9},{x:7,y:9},{x:6,y:9},{x:5,y:9}];dir=dirs.right;queue=[];score=0;index=0;ward=false;status=play?'playing':'ready';last=performance.now();spawn();update();overlay();draw();}
function update(){$('score').textContent=String(score).padStart(5,'0');$('best').textContent=String(best).padStart(5,'0');$('stats').textContent=`蛇节 ${snake.length} · 速度 ${1+Math.floor((snake.length-4)/4)} · 通关 ${Math.min(score,TARGET_SCORE)}/${TARGET_SCORE}`;$('ward').textContent=ward?'幽魂灯：已点燃 · 抵挡一次碰撞':'幽魂灯：未激活';$('foodName').textContent=foods[index][1];$('foodInfo').textContent=`吞噬获得 ${foods[index][2]} 分`;$('offer').src=sprites[foods[index][0]].toDataURL();$('offer').alt=foods[index][1]}
function overlay(){const open=status!=='playing';$('cover').hidden=!open;if(status==='ready'){$('title').textContent='地窖正在等你';$('message').textContent=`吞下祭品，达到 ${TARGET_SCORE} 分通关。避开石墙和自己的身体。`;$('start').textContent='开始游戏'}else if(status==='paused'){$('title').textContent='仪式暂停';$('message').textContent='深呼吸，然后继续。';$('start').textContent='继续游戏'}else if(status==='over'||status==='won'){$('title').textContent=status==='won'?'地窖已被吞噬':'仪式终止';$('message').textContent=status==='won'?`通关！你达到了 ${TARGET_SCORE} 分 · 本局得分 ${score}`:`本局得分 ${score} · 通关目标 ${TARGET_SCORE} · 最高分 ${best}`;$('start').textContent='再次下潜'}}
function start(){if(status==='paused'){status='playing';last=performance.now();overlay()}else reset(true);canvas.focus()}
function pause(){if(status==='playing')status='paused';else if(status==='paused')status='playing';else return;last=performance.now();overlay()}
function turn(name){if(status!=='playing')return;const next=dirs[name],prev=queue.at(-1)||dir;if(queue.length<2&&next.x!==-prev.x&&next.y!==-prev.y&&(next.x!==prev.x||next.y!==prev.y))queue.push(next)}
function finish(win=false){status=win?'won':'over';best=Math.max(best,score);try{localStorage.setItem('horror-snake-best',best)}catch{}update();overlay()}
function step(){dir=queue.shift()||dir;const head={x:snake[0].x+dir.x,y:snake[0].y+dir.y};const eat=head.x===food.x&&head.y===food.y;const body=eat?snake:snake.slice(0,-1);if(head.x<0||head.x>=18||head.y<0||head.y>=18||body.some(p=>p.x===head.x&&p.y===head.y)){if(ward){ward=false;snake.reverse();dir={x:snake[0].x-snake[1].x,y:snake[0].y-snake[1].y};queue=[];update();return}finish();return}snake.unshift(head);if(eat){score+=foods[index][2];if(foods[index][0]==='lantern')ward=true;index=(index+1)%foods.length;update();if(score>=TARGET_SCORE){finish(true);return}spawn()}else snake.pop()}
function sprite(key,x,y,size,angle=0){const im=sprites[key];if(!im)return;ctx.save();ctx.translate(x*40+20,y*40+20);ctx.rotate(angle);const scale=size/Math.max(im.width,im.height);ctx.drawImage(im,-im.width*scale/2,-im.height*scale/2,im.width*scale,im.height*scale);ctx.restore()}
function draw(){ctx.imageSmoothingEnabled=false;ctx.fillStyle='#191a17';ctx.fillRect(0,0,720,720);for(let y=0;y<18;y++)for(let x=0;x<18;x++){ctx.fillStyle=(x+y)%2?'#20211d':'#252520';ctx.fillRect(x*40+1,y*40+1,38,38);ctx.fillStyle='#41342b';if((x*7+y*13)%17===0)ctx.fillRect(x*40+6,y*40+19,12,2)}if(food){ctx.fillStyle='#873d3344';ctx.beginPath();ctx.arc(food.x*40+20,food.y*40+20,21,0,Math.PI*2);ctx.fill();sprite(foods[index][0],food.x,food.y,36)}snake.slice().reverse().forEach((p,i)=>{if(i===snake.length-1)sprite('head',p.x,p.y,44,Math.atan2(dir.y,dir.x)-Math.PI);else sprite('body',p.x,p.y,41)});if(ward){ctx.strokeStyle='#c5a16a';ctx.lineWidth=2;ctx.strokeRect(snake[0].x*40+1,snake[0].y*40+1,38,38)}}
function frame(now){if(status==='playing'&&now-last>=Math.max(90,210-Math.floor((snake.length-4)/4)*15)){last=now;step()}draw();requestAnimationFrame(frame)}
atlas.onload=()=>{for(const[key,crop]of Object.entries(crops)){const im=document.createElement('canvas');im.width=crop[2];im.height=crop[3];const c=im.getContext('2d');c.drawImage(atlas,...crop.map(v=>v*atlas.width/1600),0,0,im.width,im.height);const pixels=c.getImageData(0,0,im.width,im.height);for(let i=0;i<pixels.data.length;i+=4){const max=Math.max(...pixels.data.slice(i,i+3));if(max<28)pixels.data[i+3]=0;else for(let j=0;j<3;j++)pixels.data[i+j]=Math.min(255,pixels.data[i+j]*1.4)}c.putImageData(pixels,0,0);sprites[key]=im}reset();requestAnimationFrame(frame)};
atlas.onerror=()=>{$('title').textContent='素材加载失败';$('message').textContent='请刷新页面重试';$('start').disabled=true};
$('start').onclick=start;$('restart').onclick=()=>reset(true);$('pause').onclick=pause;
document.querySelectorAll('[data-dir]').forEach(b=>b.onclick=()=>turn(b.dataset.dir));
addEventListener('keydown',e=>{const k=e.key.toLowerCase(),map={arrowup:'up',w:'up',arrowdown:'down',s:'down',arrowleft:'left',a:'left',arrowright:'right',d:'right'};if(map[k]||k===' '){e.preventDefault();if(map[k])turn(map[k]);else pause()}if(k==='r')reset(true);if(k==='enter'&&status!=='playing'&&e.target===canvas)start()});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&status==='playing')pause()});let touch;
canvas.addEventListener('pointerdown',e=>{touch={x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointerup',e=>{if(!touch)return;const x=e.clientX-touch.x,y=e.clientY-touch.y;if(Math.max(Math.abs(x),Math.abs(y))>12)turn(Math.abs(x)>Math.abs(y)?x>0?'right':'left':y>0?'down':'up');touch=null});
