import './style.css';
const canvas=document.getElementById('gameCanvas');const ctx=canvas.getContext('2d');ctx.imageSmoothingEnabled=false;
const atlas=new Image();atlas.src='/assets/snake-atlas.png';
const N=18,CELL=40;const storedBest=Number(localStorage.getItem('snake-best'));let snake,dir,nextDir,food,score,best=Number.isFinite(storedBest)?Math.max(0,Math.round(storedBest)):0,running=true,paused=false,loop=null,combo=0,shield=0,foodIndex=0;
const foodTypes=[{name:'红苹果',desc:'基础食物 · +10',sx:80,sy:1640,sw:180,sh:180},{name:'粉桃',desc:'成长食物 · +20',sx:365,sy:1640,sw:180,sh:180},{name:'葡萄',desc:'连击食物 · +30',sx:650,sy:1640,sw:190,sh:200},{name:'柠檬',desc:'速度食物 · +40',sx:1085,sy:1640,sw:180,sh:180},{name:'药水',desc:'护盾道具 · +50',sx:1380,sy:1600,sw:220,sh:230}];
const $=id=>document.getElementById(id);const formatScore=value=>String(Math.max(0,Math.round(Number(value)||0))).padStart(5,'0');function rand(){return Math.floor(Math.random()*N)}function cellKey(p){return p.x+','+p.y}function placeFood(){do{food={x:rand(),y:rand()}}while(snake.some(p=>p.x===food.x&&p.y===food.y))}
function reset(){snake=[{x:9,y:9},{x:8,y:9},{x:7,y:9}];dir={x:1,y:0};nextDir={x:1,y:0};score=0;combo=0;shield=0;foodIndex=0;running=true;paused=false;placeFood();hideOverlay();updateUI();clearInterval(loop);loop=setInterval(tick,170);canvas.focus()}
function drawSprite(sx,sy,sw,sh,x,y,size=CELL){if(!atlas.complete)return;ctx.drawImage(atlas,sx,sy,sw,sh,x*CELL+(CELL-size)/2,y*CELL+(CELL-size)/2,size,size)}
function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#0b120b';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.strokeStyle='#182418';ctx.lineWidth=1;for(let i=0;i<=N;i++){ctx.beginPath();ctx.moveTo(i*CELL+.5,0);ctx.lineTo(i*CELL+.5,canvas.height);ctx.stroke();ctx.beginPath();ctx.moveTo(0,i*CELL+.5);ctx.lineTo(canvas.width,i*CELL+.5);ctx.stroke()}if(food){const f=foodTypes[foodIndex];drawSprite(f.sx,f.sy,f.sw,f.sh,food.x,food.y,31);ctx.fillStyle='#ffbd3b55';ctx.beginPath();ctx.arc(food.x*CELL+20,food.y*CELL+20,19+Math.sin(Date.now()/220)*2,0,Math.PI*2);ctx.fill()}snake.slice().reverse().forEach((p,i)=>{const isHead=i===snake.length-1;let sx=130,sy=650,sw=150,sh=150;if(isHead){if(dir.x===1){sx=460;sy=300;sw=230;sh=180}else if(dir.x===-1){sx=1120;sy=300;sw=230;sh=180}else if(dir.y===-1){sx=850;sy=180;sw=180;sh=230}else{sx=180;sy=180;sw=180;sh=230}}drawSprite(sx,sy,sw,sh,p.x,p.y,isHead?36:35)});if(paused){ctx.fillStyle='#070b07aa';ctx.fillRect(0,0,720,720);ctx.fillStyle='#c4f25b';ctx.font='bold 26px Courier New';ctx.textAlign='center';ctx.fillText('PAUSED',360,360)}requestAnimationFrame(draw)}
function tick(){if(!running||paused)return;dir=nextDir;const head={x:snake[0].x+dir.x,y:snake[0].y+dir.y};const hitWall=head.x<0||head.x>=N||head.y<0||head.y>=N;const hitSelf=snake.some((p,i)=>i>0&&p.x===head.x&&p.y===head.y);if(hitWall||hitSelf){if(shield){shield=0;nextDir={x:-dir.x,y:-dir.y};updateUI();return}gameOver();return}snake.unshift(head);if(head.x===food.x&&head.y===food.y){score=Math.round(score+(foodIndex+1)*10+Math.floor(combo)*2);combo++;if(foodIndex===4)shield=1;foodIndex=(foodIndex+1)%foodTypes.length;placeFood();updateUI()}else{snake.pop();combo=Math.max(0,combo-0.02)}}
function gameOver(){running=false;clearInterval(loop);score=Math.round(score);best=Math.max(best,score);localStorage.setItem('snake-best',String(best));$('overlayTitle').textContent='GAME OVER';$('overlayScore').textContent='得分 '+formatScore(score);$('overlay').classList.remove('hidden');updateUI()}
function togglePause(){if(!running)return;paused=!paused;$('pauseBtn').textContent=paused?'▶':'Ⅱ';updateUI()}
function hideOverlay(){$('overlay').classList.add('hidden')}
function updateUI(){ $('score').textContent=formatScore(score);$('bestScore').textContent=formatScore(best);$('length').textContent=String(snake.length).padStart(2,'0');$('speed').textContent=String(Math.max(1,Math.floor((snake.length-2)/3)+1)).padStart(2,'0');$('combo').textContent='×'+Math.floor(combo);$('shieldText').textContent=shield?'已激活 · 撞墙免疫':'未激活';$('shieldCount').textContent=shield?'×1':'—';const f=foodTypes[foodIndex];$('foodName').textContent=f.name;$('foodDesc').textContent=f.desc;$('foodPreview').style.backgroundPosition=`-${10+foodIndex*72}px -332px`}
function setDir(x,y){if(dir.x===-x&&dir.y===-y)return;nextDir={x,y}}
window.addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(['arrowup','arrowdown','arrowleft','arrowright',' '].includes(k))e.preventDefault();if(k==='arrowup'||k==='w')setDir(0,-1);if(k==='arrowdown'||k==='s')setDir(0,1);if(k==='arrowleft'||k==='a')setDir(-1,0);if(k==='arrowright'||k==='d')setDir(1,0);if(k===' ')togglePause();if(k==='r')reset()});$('pauseBtn').onclick=togglePause;$('restartBtn').onclick=reset;$('restartOverlay').onclick=reset;$('soundBtn').onclick=()=>{$('soundBtn').classList.toggle('muted');$('soundBtn').textContent=$('soundBtn').classList.contains('muted')?'—':'◖'};atlas.onload=()=>{reset();draw()};

